### ISSUE TITLE
[BUG]: I cant launch the launcher

### ISSUE THREAD

**Issue by Evanator05** [stephini/SMAS_Launcher#22] opened 2023-06-23 02:30 UTC
### Describe the Bug

When I try to launch the launcher I get this error

Traceback (most recent call last):
  File "launcher.pyw", line 731, in <module>
  File "launcher.pyw", line 728, in main
  File "launcher.pyw", line 626, in create_launcher_window
  File "tkinter\__init__.py", line 2136, in wm_iconbitmap
_tkinter.TclError: bitmap ".\assets\icon.ico" not defined

### Reproduction Steps

open the launcher with the 2 roms in the same folder

### Expected Behavior

I expect the launcher to open

### Actual Behavior

the launcher doesnt open

### Operating System

Windows 11

### Screenshots

![image](https://github.com/stephini/SMAS_Launcher/assets/52511742/352f8526-5c8e-4aa6-a434-1402329ade80)

**Comment by stephini** [comment] 2023-06-23 14:28
so.. this was dumb of me. rename it to launcher.exe and it should fix itself. the issue is that it checks the filename of the executable...

**Comment by lionelr96** [comment] 2023-06-26 02:06
I had a similar problem but upon renaming the file, all I see is a blank blue window alongside a smaller white window saying "Error: Failed to play audio"... any fix for this?

**Comment by Evanator05** [comment] 2023-06-26 03:03
> I had a similar problem but upon renaming the file, all I see is a blank blue window alongside a smaller white window saying "Error: Failed to play audio"... any fix for this?

the issue is that the library they use for audio doesn't install properly, even if you try installing it with pip it doesn't work

**Comment by stephini** [comment] 2023-06-27 18:36
Evan this is not correct. They were using the exe, which has the modules baked in. Also the sound is handled by pygame so it's doubly not the case. The issue is when you are using exe it must be named launcher.exe any other error will cause it to fail detecting the assets folder.

**Closed by stephini** 2023-06-27 18:36 UTC
Labels: bug, Kanban Accepted, Kanban Todo
